branches:
  only:
    - master
language: c
compiler: gcc
install:
 - sudo apt-get update -qq
 - sudo apt-get install --no-install-recommends -y doxygen graphviz valgrind
 - wget http://ftp.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
 - tar xf lcov_1.11.orig.tar.gz
 - sudo make -C lcov-1.11/ install
 - rm -rf lcov-1.11
 - lcov --version
script: make test
after_success: ./build_pages.sh
env:
  global:
    - secure: "YMy+UayddGOGRp4v7Qf4g+1kpWwBBq8nrPt46ZKI/vYYDcdoiYuaUvLNVbJgbKv9Bldk3/hqrP+XAepBoVRIWE6rZlriPciPmADW8xKWhfBbgN11q4iryRJh3KsjweKbA/IU13uUL/o+kPJmbqZcBOOV6QSTQt0MVVQH1NW8p5U="
